package smartfile

import (
	"strings"
	"testing"
)

func TestGenerateEditorConfig(t *testing.T) {
	tests := []struct {
		name    string
		options map[string]string
	}{
		{
			name:    "Nil options",
			options: nil,
		},
		{
			name:    "Empty options",
			options: map[string]string{},
		},
		{
			name:    "With arbitrary options",
			options: map[string]string{"language": "Go", "app_name": "test"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateEditorConfig(tt.options)

			// Verify header
			if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
				t.Errorf("GenerateEditorConfig() output missing header prefix")
			}

			// Verify required EditorConfig directives and sections
			expectedKeywords := []string{
				"root = true",
				"charset = utf-8",
				"end_of_line = lf",
				"insert_final_newline = true",
				"trim_trailing_whitespace = true",
				"indent_style = space",
				"indent_size = 2",
				"[*.{js,jsx,ts,tsx,json}]",
				"[*.{py,rb}]",
				"[*.go]",
				"indent_style = tab",
				"[Makefile]",
			}

			for _, kw := range expectedKeywords {
				if !strings.Contains(result, kw) {
					t.Errorf("GenerateEditorConfig() output missing expected directive/section: %q", kw)
				}
			}
		})
	}
}

func TestGenerateEnvFile(t *testing.T) {
	tests := []struct {
		name            string
		options         map[string]string
		expectedAppName string
	}{
		{
			name:            "Nil options defaults to my_app",
			options:         nil,
			expectedAppName: "APP_NAME=my_app",
		},
		{
			name:            "Empty options defaults to my_app",
			options:         map[string]string{},
			expectedAppName: "APP_NAME=my_app",
		},
		{
			name:            "Custom app_name option",
			options:         map[string]string{"app_name": "awesome_service"},
			expectedAppName: "APP_NAME=awesome_service",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateEnvFile(tt.options)

			if !strings.HasPrefix(result, "# Environment Configuration\n# Generated by DevCLI\n") {
				t.Errorf("GenerateEnvFile() output missing expected header")
			}

			if !strings.Contains(result, tt.expectedAppName) {
				t.Errorf("GenerateEnvFile() output expected %q, got output:\n%s", tt.expectedAppName, result)
			}
		})
	}
}

func TestGenerateGitignore(t *testing.T) {
	tests := []struct {
		name             string
		options          map[string]string
		expectedContains []string
	}{
		{
			name:             "Node.js language",
			options:          map[string]string{"language": "Node.js"},
			expectedContains: []string{"node_modules/", ".next/", "coverage/"},
		},
		{
			name:             "JavaScript language",
			options:          map[string]string{"language": "JavaScript"},
			expectedContains: []string{"node_modules/"},
		},
		{
			name:             "TypeScript language",
			options:          map[string]string{"language": "TypeScript"},
			expectedContains: []string{"node_modules/"},
		},
		{
			name:             "Python language",
			options:          map[string]string{"language": "Python"},
			expectedContains: []string{"__pycache__/", "*.py[cod]", "venv/"},
		},
		{
			name:             "Go language",
			options:          map[string]string{"language": "Go"},
			expectedContains: []string{"*.exe", "*.test", "vendor/"},
		},
		{
			name:             "Rust language",
			options:          map[string]string{"language": "Rust"},
			expectedContains: []string{"target/", "Cargo.lock"},
		},
		{
			name:             "Default / unknown language",
			options:          map[string]string{"language": "Unknown"},
			expectedContains: []string{".git/", ".env", "dist/"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateGitignore(tt.options)

			if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
				t.Errorf("GenerateGitignore() output missing DevCLI header")
			}

			for _, expected := range tt.expectedContains {
				if !strings.Contains(result, expected) {
					t.Errorf("GenerateGitignore() output missing expected string %q", expected)
				}
			}
		})
	}
}

func TestGenerateDockerfile(t *testing.T) {
	tests := []struct {
		name             string
		options          map[string]string
		expectedContains []string
	}{
		{
			name:             "Node.js",
			options:          map[string]string{"language": "Node.js"},
			expectedContains: []string{"FROM node:18-alpine AS base", "npm run build"},
		},
		{
			name:             "JavaScript",
			options:          map[string]string{"language": "JavaScript"},
			expectedContains: []string{"FROM node:18-alpine AS base"},
		},
		{
			name:             "Python",
			options:          map[string]string{"language": "Python"},
			expectedContains: []string{"FROM python:3.11-slim AS base", "requirements.txt"},
		},
		{
			name:             "Go",
			options:          map[string]string{"language": "Go"},
			expectedContains: []string{"FROM golang:1.21-alpine AS builder", "go build"},
		},
		{
			name:             "Default",
			options:          map[string]string{"language": "C++"},
			expectedContains: []string{"FROM ubuntu:22.04"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateDockerfile(tt.options)

			if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
				t.Errorf("GenerateDockerfile() output missing header")
			}

			for _, expected := range tt.expectedContains {
				if !strings.Contains(result, expected) {
					t.Errorf("GenerateDockerfile() output missing expected string %q", expected)
				}
			}
		})
	}
}

func TestGenerateMakefile(t *testing.T) {
	tests := []struct {
		name             string
		options          map[string]string
		expectedContains []string
	}{
		{
			name:             "Go",
			options:          map[string]string{"language": "Go"},
			expectedContains: []string{"go build", "go test", "gofmt"},
		},
		{
			name:             "Python",
			options:          map[string]string{"language": "Python"},
			expectedContains: []string{"pytest", "flake8", "black ."},
		},
		{
			name:             "Default",
			options:          map[string]string{"language": "Java"},
			expectedContains: []string{"Building...", "Running tests..."},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateMakefile(tt.options)

			if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
				t.Errorf("GenerateMakefile() output missing header")
			}

			for _, expected := range tt.expectedContains {
				if !strings.Contains(result, expected) {
					t.Errorf("GenerateMakefile() output missing expected string %q", expected)
				}
			}
		})
	}
}

func TestGenerateGitHubActions(t *testing.T) {
	tests := []struct {
		name             string
		options          map[string]string
		expectedContains []string
	}{
		{
			name:             "Node.js",
			options:          map[string]string{"language": "Node.js"},
			expectedContains: []string{"actions/setup-node", "npm test"},
		},
		{
			name:             "JavaScript",
			options:          map[string]string{"language": "JavaScript"},
			expectedContains: []string{"actions/setup-node"},
		},
		{
			name:             "Python",
			options:          map[string]string{"language": "Python"},
			expectedContains: []string{"actions/setup-python", "pytest"},
		},
		{
			name:             "Go",
			options:          map[string]string{"language": "Go"},
			expectedContains: []string{"actions/setup-go", "go test"},
		},
		{
			name:             "Default",
			options:          map[string]string{"language": "Ruby"},
			expectedContains: []string{"name: CI", "Run tests"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := GenerateGitHubActions(tt.options)

			if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
				t.Errorf("GenerateGitHubActions() output missing header")
			}

			for _, expected := range tt.expectedContains {
				if !strings.Contains(result, expected) {
					t.Errorf("GenerateGitHubActions() output missing expected string %q", expected)
				}
			}
		})
	}
}

func TestGenerateDockerCompose(t *testing.T) {
	result := GenerateDockerCompose(nil)

	if !strings.HasPrefix(result, "# Generated by DevCLI\n") {
		t.Errorf("GenerateDockerCompose() output missing header")
	}

	expectedKeywords := []string{
		"version: '3.8'",
		"postgres:15-alpine",
		"redis:7-alpine",
	}

	for _, kw := range expectedKeywords {
		if !strings.Contains(result, kw) {
			t.Errorf("GenerateDockerCompose() output missing expected keyword: %q", kw)
		}
	}
}

func TestTemplatesList(t *testing.T) {
	if len(Templates) == 0 {
		t.Fatalf("Templates slice is empty")
	}

	expectedCount := 8
	if len(Templates) != expectedCount {
		t.Errorf("Expected %d templates, got %d", expectedCount, len(Templates))
	}

	for _, tmpl := range Templates {
		if tmpl.Name == "" {
			t.Errorf("Template with empty Name found")
		}
		if tmpl.Generator == nil {
			t.Errorf("Template %s has nil Generator", tmpl.Name)
		} else {
			output := tmpl.Generator(map[string]string{"language": "Go", "app_name": "test_app"})
			if output == "" {
				t.Errorf("Template %s Generator returned empty string", tmpl.Name)
			}
		}
	}
}
