package smartfile

import (
	"fmt"
)

type FileTemplate struct {
	Name        string
	Description string
	Extension   string
	Generator   func(options map[string]string) string
}

var Templates = []FileTemplate{
	{
		Name:        ".env",
		Description: "Environment variables template",
		Extension:   ".env",
		Generator:   GenerateEnvFile,
	},
	{
		Name:        ".gitignore",
		Description: "Git ignore patterns",
		Extension:   ".gitignore",
		Generator:   GenerateGitignore,
	},
	{
		Name:        "Dockerfile",
		Description: "Docker container configuration",
		Extension:   "",
		Generator:   GenerateDockerfile,
	},
	{
		Name:        ".editorconfig",
		Description: "Editor configuration",
		Extension:   ".editorconfig",
		Generator:   GenerateEditorConfig,
	},
	{
		Name:        "Makefile",
		Description: "Build automation",
		Extension:   "",
		Generator:   GenerateMakefile,
	},
	{
		Name:        "GitHub Actions",
		Description: "CI/CD workflow",
		Extension:   ".yml",
		Generator:   GenerateGitHubActions,
	},
	{
		Name:        "docker-compose.yml",
		Description: "Multi-container Docker setup",
		Extension:   ".yml",
		Generator:   GenerateDockerCompose,
	},
	{
		Name:        "Custom File (AI)",
		Description: "Generate any file content using AI assistant",
		Extension:   "",
		Generator:   func(_ map[string]string) string { return "(AI content will be generated...)" },
	},
}

func GenerateEnvFile(options map[string]string) string {
	template := `# Environment Configuration
# Generated by DevCLI

# Application
APP_NAME=%s
APP_ENV=development
DEBUG=true
PORT=3000

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
# DATABASE_URL=mysql://user:password@localhost:3306/dbname
# DATABASE_URL=mongodb://localhost:27017/dbname

# Redis
REDIS_URL=redis://localhost:6379

# API Keys
API_KEY=your_api_key_here
SECRET_KEY=your_secret_key_here

# Email
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your_email@gmail.com
SMTP_PASS=your_password

# AWS (Optional)
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_REGION=us-east-1

# Other Services
# STRIPE_API_KEY=
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
`
	appName := options["app_name"]
	if appName == "" {
		appName = "my_app"
	}
	return fmt.Sprintf(template, appName)
}

func GenerateGitignore(options map[string]string) string {
	lang := options["language"]

	base := `# Editor directories and files
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# OS
Thumbs.db
`

	switch lang {
	case "Node.js", "JavaScript", "TypeScript":
		return "# Generated by DevCLI\n" + base + `
# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
dist/
build/
.next/
.nuxt/
.cache/
.env.local
.env.*.local
*.log

# Testing
coverage/
.nyc_output/
`
	case "Python":
		return "# Generated by DevCLI\n" + base + `
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
.venv
pip-log.txt
pip-delete-this-directory.txt
.pytest_cache/
.coverage
htmlcov/
*.egg-info/
dist/
build/
`
	case "Go":
		return "# Generated by DevCLI\n" + base + `
# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
vendor/
`
	case "Rust":
		return "# Generated by DevCLI\n" + base + `
# Rust
target/
Cargo.lock
**/*.rs.bk
`
	default:
		return "# Generated by DevCLI\n" + base + `
# Git
.git/

# Logs
*.log

# Environment
.env
.env.local

# Build outputs
dist/
build/
out/
`
	}
}

func GenerateDockerfile(options map[string]string) string {
	lang := options["language"]

	switch lang {
	case "Node.js", "JavaScript":
		return "# Generated by DevCLI\n" + `# Node.js Dockerfile
FROM node:18-alpine AS base

# Dependencies stage
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

# Build stage
FROM base AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production stage
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 appuser

COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package.json ./

USER appuser
EXPOSE 3000
CMD ["node", "dist/index.js"]
`
	case "Python":
		return "# Generated by DevCLI\n" + `# Python Dockerfile
FROM python:3.11-slim AS base

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create non-root user
RUN useradd -m -u 1001 appuser
USER appuser

EXPOSE 8000

CMD ["python", "main.py"]
`
	case "Go":
		return "# Generated by DevCLI\n" + `# Go Dockerfile (Multi-stage)
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Production stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy binary from builder
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
`
	default:
		return "# Generated by DevCLI\n" + `# Dockerfile
FROM ubuntu:22.04

WORKDIR /app

COPY . .

# Install dependencies
# RUN apt-get update && apt-get install -y <packages>

EXPOSE 8080

CMD ["./start.sh"]
`
	}
}

func GenerateEditorConfig(options map[string]string) string {
	return "# Generated by DevCLI\n" + `# EditorConfig helps maintain consistent coding styles
# https://editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.{js,jsx,ts,tsx,json}]
indent_size = 2

[*.{py,rb}]
indent_size = 4

[*.go]
indent_style = tab
indent_size = 4

[*.md]
trim_trailing_whitespace = false

[Makefile]
indent_style = tab
`
}

func GenerateMakefile(options map[string]string) string {
	lang := options["language"]

	switch lang {
	case "Go":
		return "# Generated by DevCLI\n" + `.PHONY: build test clean run

APP_NAME=myapp
BUILD_DIR=./build

build:
	go build -o $(BUILD_DIR)/$(APP_NAME) .

test:
	go test -v ./...

clean:
	rm -rf $(BUILD_DIR)

run:
	go run .

fmt:
	gofmt -w .

lint:
	go vet ./...
`
	case "Python":
		return "# Generated by DevCLI\n" + `.PHONY: install test clean run lint format

install:
	pip install -r requirements.txt

test:
	pytest

clean:
	find . -type d -name '__pycache__' -exec rm -rf {} +
	find . -type f -name '*.pyc' -delete

run:
	python main.py

lint:
	flake8 .

format:
	black .
`
	default:
		return "# Generated by DevCLI\n" + `.PHONY: build test clean run

build:
	@echo "Building..."

test:
	@echo "Running tests..."

clean:
	@echo "Cleaning..."

run:
	@echo "Running..."
`
	}
}

func GenerateGitHubActions(options map[string]string) string {
	lang := options["language"]

	switch lang {
	case "Node.js", "JavaScript":
		return "# Generated by DevCLI\n" + `name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build
`
	case "Python":
		return "# Generated by DevCLI\n" + `name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
`
	case "Go":
		return "# Generated by DevCLI\n" + `name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...
`
	default:
		return "# Generated by DevCLI\n" + `name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: echo "Add your test commands here"
`
	}
}

func GenerateDockerCompose(options map[string]string) string {
	return "# Generated by DevCLI\n" + `version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
`
}
